"""Initial

Revision ID: 80d8da42b17a
Revises:
Create Date: 2025-10-01 13:58:01.011699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.datasources.db.fields import EthereumAddressType, Uint256Type

# revision identifiers, used by Alembic.
revision: str = "80d8da42b17a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "multisigtransaction",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("safe_tx_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("chain_id", Uint256Type(), nullable=False),
        sa.Column(
            "safe",
            EthereumAddressType(),
            nullable=False,
        ),
        sa.Column(
            "nonce",
            Uint256Type(),
            nullable=False,
        ),
        sa.Column(
            "proposer",
            EthereumAddressType(),
            nullable=True,
        ),
        sa.Column(
            "proposed_by_delegate",
            EthereumAddressType(),
            nullable=True,
        ),
        sa.Column("tx_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column(
            "to",
            EthereumAddressType(),
            nullable=True,
        ),
        sa.Column(
            "value",
            Uint256Type(),
            nullable=False,
        ),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("operation", sa.SmallInteger(), nullable=False),
        sa.Column(
            "safe_tx_gas",
            Uint256Type(),
            nullable=False,
        ),
        sa.Column(
            "base_gas",
            Uint256Type(),
            nullable=False,
        ),
        sa.Column(
            "gas_price",
            Uint256Type(),
            nullable=False,
        ),
        sa.Column(
            "gas_token",
            EthereumAddressType(),
            nullable=True,
        ),
        sa.Column(
            "refund_receiver",
            EthereumAddressType(),
            nullable=True,
        ),
        sa.Column("signatures", sa.LargeBinary(), nullable=True),
        sa.Column("failed", sa.Boolean(), nullable=True),
        sa.Column("origin", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("safe_tx_hash"),
    )
    op.create_index(
        "ix__multisigtransaction_safe_sorted",
        "multisigtransaction",
        ["safe", sa.literal_column("nonce DESC"), sa.literal_column("created DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_multisigtransaction_created"),
        "multisigtransaction",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multisigtransaction_failed"),
        "multisigtransaction",
        ["failed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multisigtransaction_nonce"),
        "multisigtransaction",
        ["nonce"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multisigtransaction_safe"),
        "multisigtransaction",
        ["safe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multisigtransaction_to"), "multisigtransaction", ["to"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_multisigtransaction_to"), table_name="multisigtransaction")
    op.drop_index(op.f("ix_multisigtransaction_safe"), table_name="multisigtransaction")
    op.drop_index(
        op.f("ix_multisigtransaction_nonce"), table_name="multisigtransaction"
    )
    op.drop_index(
        op.f("ix_multisigtransaction_failed"), table_name="multisigtransaction"
    )
    op.drop_index(
        op.f("ix_multisigtransaction_created"), table_name="multisigtransaction"
    )
    op.drop_index(
        "ix__multisigtransaction_safe_sorted", table_name="multisigtransaction"
    )
    op.drop_table("multisigtransaction")
    # ### end Alembic commands ###
